import { faker } from '@faker-js/faker'
import reviewPage from '@Model/Review_Product_Page'

describe('Review Product', () => {
  beforeEach(() => {
    cy.visit('')
  })
  let namePerson = faker.person.fullName()
  let phoneNo = `628` + faker.finance.accountNumber(9)
  let date = new Date().toLocaleDateString()

  it('Review Product with input all answers, should succeed', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(namePerson)
    cy.get(reviewPage.phoneNumber).type(phoneNo)
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.thankYouMessage)
      .should('be.visible')
      .and('contain', 'Your response has been successfully recorded.')
    cy.get(reviewPage.saveBotton).should('be.visible')
  })
  it('Review Product with input submitted Phone Number, should succeed', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(faker.person.fullName())
    cy.get(reviewPage.phoneNumber).type(phoneNo)
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.thankYouMessage)
      .should('be.visible')
      .and('contain', 'Your response has been successfully recorded.')
    cy.get(reviewPage.saveBotton).should('be.visible')
  })
  it('Review Product without input name, should fail', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(9))
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'This question is required.')
    cy.contains('1 question(s) need to be completed before submitting: Question 1.').should('be.visible')
  })
  it('Review Product without input Phone Number, should fail', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(faker.person.fullName())
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'This question is required.')
    cy.contains('1 question(s) need to be completed before submitting: Question 2.').should('be.visible')
  })
  it('Review Product without input answer to question 3, should fail', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(faker.person.fullName())
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(9))
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'This question is required.')
    cy.contains('1 question(s) need to be completed before submitting: Question 3.').should('be.visible')
  })
  it('Review Product without input Rate, should fail', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(faker.person.fullName())
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(9))
    cy.get(reviewPage.expensive).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'This question is required.')
    cy.contains('1 question(s) need to be completed before submitting: Question 4.').should('be.visible')
  })
  it('Review Product without input Review date, should fail', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(faker.person.fullName())
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(9))
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'This question is required.')
    cy.contains('1 question(s) need to be completed before submitting: Question 5.').should('be.visible')
  })
  it('Review Product without input all answers, should fail', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'This question is required.')
    cy.contains(
      '5 question(s) need to be completed before submitting: Question 1,Question 2,Question 3,Question 4,Question 5.'
    ).should('be.visible')
  })
  it.skip('Review Product with symbol input on name field, should fail #notDeveloped', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type('/m.,.,m.`12~!@')
    cy.get(reviewPage.phoneNumber).type(phoneNo)
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'Invalid input')
   })
  it.skip('Review Product with alphabet input on Phone Number, should fail #notDeveloped', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(namePerson)
    cy.get(reviewPage.phoneNumber).type(namePerson)
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'Invalid input')
   })
  it.skip('Review Product with less than minimum input on Phone Number, should fail #notDeveloped', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(namePerson)
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(2))
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'Invalid input')
  })
  it.skip('Review Product with more than maximum input on Phone Number, should fail #notDeveloped', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(namePerson)
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(25))
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(date)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'Invalid input')
  })
  it.skip('Review Product with future date, should fail #notDeveloped', { retries: 2 }, () => {
    let currentDate = new Date(new Date().toLocaleDateString());
    currentDate.setDate(currentDate.getDate() + 1);
    let tomorrowDate = currentDate.toLocaleDateString();
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(namePerson)
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(25))
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(tomorrowDate)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'Invalid input')
  })
  it.skip('Review Product with past date, should fail #notDeveloped', { retries: 2 }, () => {
    let currentDate = new Date(new Date().toLocaleDateString());
    currentDate.setDate(currentDate.getDate() - 1);
    let backDate = currentDate.toLocaleDateString();
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.get(reviewPage.fullName).type(namePerson)
    cy.get(reviewPage.phoneNumber).type(`628` + faker.finance.accountNumber(25))
    cy.get(reviewPage.affordable).click()
    cy.get(reviewPage.start4).click()
    cy.get(reviewPage.date).dblclick().type(backDate)
    cy.get(reviewPage.submitButton).click().wait(2000)
    cy.get(reviewPage.validationError).should('be.visible').and('contain', 'Invalid input')
  })
  it.skip('Report abuse without violation and comment input, should fail #notDeveloped', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.xpath(reviewPage.reportAbuse).click().wait(2000)
    cy.contains("Report Abuse").should('be.visible')
    cy.xpath(reviewPage.submitAbuse).click()
    cy.contains("Your report was submitted.").should('be.visible')
  })
  it('Report abuse with choosing Phishing on violation, should succeed', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.xpath(reviewPage.reportAbuse).click().wait(2000)
    cy.contains("Report Abuse").should('be.visible')
    cy.get(reviewPage.phishing).click()
    cy.get(reviewPage.comment).type(faker.lorem.text())
    cy.xpath(reviewPage.submitAbuse).click()
    cy.contains("Your report was submitted.").should('be.visible')
    cy.url().should('include', '#View=ReportAbuse')
  })
  it('Report abuse with choosing Copyright infringement on violation, should succeed', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.xpath(reviewPage.reportAbuse).click().wait(2000)
    cy.contains("Report Abuse").should('be.visible')
    cy.get(reviewPage.contentInfringement).click()
    cy.contains("Report copyright infringement to Microsoft").should('be.visible')
  })
  it('Report abuse with choosing other on violation, should succeed', { retries: 2 }, () => {
    cy.get(reviewPage.headerPage).should('be.visible').wait(2000)
    cy.xpath(reviewPage.reportAbuse).click().wait(2000)
    cy.contains("Report Abuse").should('be.visible')
    cy.get(reviewPage.otherabuse).click()
    cy.get(reviewPage.comment).type(faker.lorem.text())
    cy.xpath(reviewPage.submitAbuse).click()
    cy.contains("Your report was submitted.").should('be.visible')
    cy.url().should('include', '#View=ReportAbuse')
  })
})
