export default {
  headerPage: '#FormTitleId_titleAriaId',
  fullName: ':nth-child(1) > .-bU-48 > .-a-52 > .-nl-63 > .-_W-62',
  phoneNumber: ':nth-child(2) > .-bU-48 > .-a-52 > .-nl-63 > .-_W-62',
  affordable: 'input[value="Affordable"]',
  expensive: 'input[value="Expensive"]',
  other: 'input[name="r8bc17b753f0048ecb03794ef45037bb7"][aria-label="Other answer"]',
  start4: 'span[aria-label="4 Star"]',
  date: '#DatePicker0-label',
  submitButton: '[data-automation-id="submitButton"]',
  validationError: '[data-automation-id="validationError"]',
  errorMessage: '.--Y-240',
  thankYouMessage: '[data-automation-id="thankYouMessage"]',
  saveBotton: '[data-automation-id="saveAndEditButton"]',
  reportAbuse : '//a[contains(text(),"Report abuse")]',
  phishing: '#Phishing',
  contentInfringement : '#ContentInfringement',
  otherabuse :'#Other',
  comment : '.-_W-62',
  submitAbuse : '//button[normalize-space()="Submit"]'
}
